project:
  type: website

website:
  title: "Emily Sundberg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: "Projects"
      - href: cv.qmd
        text: "CV"
      - href: contact.qmd
        text: "Contact"
      - about.qmd


format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true



