project:
  type: website

website:
  title: "Emily Sundberg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: "Projects"
      - href: cv.qmd
        text: "CV"
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



