project:
  type: website

website:
  title: "Emily Sundberg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "About Me"
      - href: experience.qmd
        text: "Experience"
      - href: cv.qmd
        text: "CV"
      - href: contact.qmd
        text: "Contact"
      


format:
  html:
    theme: flatly
    css: styles.css
    toc: false



